GauravKarakoti/Colour-Segmentation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Closes #12 
Added issue template and PR template to the repository
> Added pr and issue template

- .gitignore
- img_segment.py
- segment.py
Title : Add Error Handling for File I/O
Closes #6 
This pull request includes changes to improve error handling and user feedback in the `img_segment.py` and `segment.py` files. The most important changes include adding checks to ensure files can be opened and providing informative error messages if they cannot be opened.
Error handling improvements:
* [`img_segment.py`](diffhunk://#diff-edb8f3b129c3b13bb610448147a08d7f4a0807c43e57f02e5e75f3c134066eedL7-R13): Added a check to verify if the image file can be opened and provided an error message if it cannot.
* [`segment.py`](diffhunk://#diff-055f4e62558f5326938f7dbe96b8b8ac992924586b895304ef285ab27d2d49d9L5-R11): Added a check to verify if the video file can be opened and provided an error message if it cannot.
User feedback improvements: …
> Add Error Handling for File I/O

- img_segment.py
- segment.py
Title : Allow Configurable File Paths
Closes #3 
This pull request updates the `img_segment.py` and `segment.py` files to improve user input handling and window display properties. The most important changes include adding command-line argument parsing, checking for file existence, and ensuring the display windows are always on top.
Enhancements to user input handling:
* [`img_segment.py`](diffhunk://#diff-edb8f3b129c3b13bb610448147a08d7f4a0807c43e57f02e5e75f3c134066eedR3-R36): Added command-line argument parsing for the image file path and a check to ensure the file exists before proceeding.
* [`segment.py`](diffhunk://#diff-055f4e62558f5326938f7dbe96b8b8ac992924586b895304ef285ab27d2d49d9R3-R31): Added command-line argument parsing for the video file path and a check to ensure the file …
> Allow Configurable File Paths

- palette.py
Title :  Feature Enhancements
Closes #13 
This pull request includes changes to the `palette.py` file to enhance the color segmentation feature. The most important changes include adding functionality to display the current RGB values on the image, saving the selected color to a file, and improving the user interface.
Enhancements to color segmentation feature:
In `palette.py`: 
* Added a `color_img` variable to create an image filled with the selected color.
* Displayed the current RGB values on the image using `cv2.putText`.
* Implemented a feature to save the selected color as an image file when the 's' key is pressed.
* Improved the user interface by ensuring the color segmentation window updates correctly and handles keypress events. …
> feat: RGB display and save functionality

- palette.py
Title : Text Visibility on Bright Backgrounds
Closes #22 
This pull request includes a change to the `palette.py` file to improve the readability of text based on the background color. The most important change is the calculation of the brightness (luminance) to determine the appropriate text color.
Improvements to text readability:
* `palette.py`: Added luminance calculation to determine whether to use black or white text for better readability based on the background color.
Yes
> Text Visibility on Bright Backgrounds

- README.md
Title : README File Updated 
Closes #8 
I did updated the README file by adding certain emojis and making it more descriptive for beginners.
I am contributing under Apertre 2.0
> # 8 README File Updated 

- img_segment.py
Title :Fix
Closes #4
Just needed to change the 255 to 179 range and all set!
Apertre 2.0 contributor
> Corrected Upper Hue Trackbar Range in img_segment.py

- img_segment.py
- segment.py
- segmentation_utils.py
Title : Refactor : used the functions from segmentation_utils.py in segment.py
This pull request includes several changes aimed at simplifying the codebase and enhancing functionality by utilizing utility functions from `segmentation_utils`. The most important changes include replacing specific imports with wildcard imports, refactoring video processing logic, and updating the display window creation logic.
Refactoring imports and video processing:
* `img_segment.py`: Replaced specific imports from `segmentation_utils` with a wildcard import to simplify the import statement.
* `segment.py`: Replaced specific imports from `segmentation_utils` with a wildcard import and refactored the video processing logic to use utility functions such as `load_video`, `create_display_windows`, …
> Refactor : used the functions from segmentation_utils.py in segment.py

- img_segment.py
- segment.py
- segmentation_utils.py
Title : Segmentation Utility Code Improvement
Closes #42 
This pull request includes several updates to the image and video segmentation scripts to improve error handling, code readability, and functionality. The most important changes include adding exception handling for file loading, improving the `create_trackbars` function, and refining the display and mask application functions.
* `img_segment.py` and `segment.py`: Added `try-except` blocks to handle `FileNotFoundError` and other exceptions when loading images and videos.
* `segmentation_utils.py`: 
* Updated `load_image` and `load_video` functions to raise exceptions instead of printing error messages.
* Added `release_video` function to safely release the `VideoCapture` object.
* `segmentation_utils.py`:
*  Modified …
> Segmentation Utility Code Improvements

- .vscode/settings.json
- img_segment.py
- palette.py
- segment.py
Title : Added code comments
Closes #7 
Added code comments in the .py files
> added code comments

- Contributing.md
- Dockerfile
Title : Dockerize the application
Closes #9
This pull request includes the addition of a `Dockerfile` to the project, which sets up a Docker environment for running a Python application. The most important changes include specifying the base image, setting the working directory, installing necessary dependencies, and configuring the entry point for the application.
Docker environment setup:
* `Dockerfile`: Added a new `Dockerfile` that uses `python:3.9-slim` as the base image, sets the working directory to `/app`, installs necessary system libraries, sets the `DISPLAY` environment variable, copies the `requirements.txt` file and installs Python dependencies, copies the application files, and sets the entry point to run `palette.py` using Python.
**GUI-based** visualization via X11 …
> Dockerize the application

- palette.py
Title : Improve UI and code structure in palette.py
Closes #39
The script has been refactored into modular functions, improving readability and maintainability by separating tasks such as creating the color palette window, retrieving trackbar values, calculating luminance, updating the display, and handling key events. Clear on-screen instructions inform users how to interact with the program, including using trackbars to select colors and pressing ‘S’ to save or ‘ESC’ to exit. Inline documentation further clarifies functionality. Error handling has been implemented to manage issues like failing to save images due to file permission errors and detecting window closure to prevent crashes. Overall, the script is now well-structured, user-friendly, and robust. 🚀
> improved ui in palette.py

- segmentation_utils.py
Title : Critical Fixes Needed for Color Segmentation in HSV Space
Closes #16 
This pull request includes changes to the `segmentation_utils.py` file to add a new function for resizing images while maintaining their aspect ratio and to update the existing `load_image` function to use this new resizing method.
Key changes:
* Added `resize_with_aspect_ratio` function to resize images while maintaining their aspect ratio.
* Updated `load_image` function to use `resize_with_aspect_ratio` for resizing images to a width of 512 pixels.
Yes, Apertre2.0
> Critical Fixes Needed for Color Segmentation in HSV Space

- img_segment.py
- segment.py
- segmentation_utils.py
Title : Limited error handling for invalid/corrupted media files
Closes #47 
This pull request includes significant improvements to error handling and validation in the image and video segmentation utilities. The most important changes include expanding the types of exceptions caught, adding a new utility function to check file access, and enhancing the validation and error messages for loading images and videos.
* `img_segment.py`: Expanded the types of exceptions caught when loading an image to include `ValueError`, `PermissionError`, and `RuntimeError`.
* `segment.py`: Expanded the types of exceptions caught when loading a video to include `FileNotFoundError`, `ValueError`, `PermissionError`, and `RuntimeError`.
* `segmentation_utils.py`: Added a new function `check_file_access` to …
> Limited error handling for invalid/corrupted media files

- img_segment.py
- palette.py
- segment.py
- segmentation_utils.py
Title : Critical Hue Wrapping Issue in HSV Segmentation and Suggested Enhancements
Closes #51 
1. **File Access Validation**: Added a `check_file_access()` function to verify the existence, validity, and readability of files before processing.
2. **Image & Video Loading**:
- Enhanced `load_image()` and `load_video()` functions for better error handling and support for resizing images to a fixed width (512px).
3. **Aspect Ratio Resizing**: Introduced a `resize_with_aspect_ratio()` function to ensure images and videos maintain their aspect ratio while resizing.
4. **Trackbars for HSV Range**:
- Added trackbars for selecting HSV (Hue, Saturation, Value) ranges interactively.
- Fixed the HSV range handling to correctly account for hue wrapping (e.g., red colors across the 180° boundary).
5. …
> Critical Hue Wrapping Issue in HSV Segmentation and Suggested Enhancements

- segmentation_utils.py
Closes #40 
https://github.com/user-attachments/assets/e424d203-b4bf-4b86-89c4-938d016a8c8c
> Inconsistent Window Naming Across Segmentation Modes

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- README.md
- tests/test_utils.py
Title : workflow for continious integration 
Closes #10 
i added workflows for linting , integration and written tests , also changed the documentation as per what i have been told to do so.
> ci workflows

- img_segment.py
- palette.py
- segment.py
> Inability to Save Segmentation Results

- img_segment.py
- segment.py
> error handling

- img_segment.py
- segment.py
> hsv space conversion

- img_segment.py
- palette.py
Title : Enhancements and Improvements for Color Palette Application
Closes #50 
This pull request includes several enhancements and new features to the `palette.py` file, improving the user interface, adding new functionalities, and ensuring better error handling. The most important changes include adding GUI popups for user input, updating the display with background rectangles behind text, and introducing new keyboard shortcuts for various operations.
* `palette.py`: Added background rectangles behind the text to improve readability, and adjusted the display size to accommodate the changes.
* `palette.py`: Introduced a GUI popup to ask for filenames when saving images, allowing users to define custom filenames.
* `palette.py`: Added new keyboard shortcuts for resetting trackbar values …
> Enhancements and Improvements for Color Palette Application

- .gitignore
- segment.py
Title : fix Bugs in Video Processing Loop and Trackbar Inconsistencies
Closes #63 
This pull request includes significant changes to the `segment.py` file to improve video processing and output handling. The most important changes include adding new command-line arguments for output video path and frame rate, improving error handling, and enhancing the video processing loop to write combined frames to the output video.
Enhancements to command-line arguments and error handling:
* Added new command-line arguments `--output` and `--fps` for specifying the output video path and frames per second, respectively.
* Improved error handling for video file loading by checking if the video file is opened successfully.
Improvements to video processing:
* Initialized frame dimensions and created a …
> fix Bugs in Video Processing Loop and Trackbar Inconsistencies

- img_segment.py
- palette.py
- segment.py
Title : Uncontrolled CPU Usage in Processing Loops
Closes #69 
This pull request includes changes to improve frame rate control and reduce CPU usage in three scripts: `img_segment.py`, `palette.py`, and `segment.py`. The most important changes include the addition of frame rate control settings, the introduction of a slight delay in keypress event handling, and the implementation of elapsed time calculation and sleep to maintain the target frame rate.
Frame rate control improvements:
* [`img_segment.py`](diffhunk://#diff-edb8f3b129c3b13bb610448147a08d7f4a0807c43e57f02e5e75f3c134066eedR77-R83): Added frame rate control settings and implemented elapsed time calculation and sleep to maintain the target frame rate.
* [`palette.py`](diffhunk://#diff-fe7b2b69aa3ba88008782d374bcf7e85a3fe2f3c82810 …
> Uncontrolled CPU Usage in Processing Loops

- README.md
Title : scroll to top button
Closes #82 
Added scroll to top button in the readme
> scroll to top button

- segment.py
Title : feat add Pause Option
Closes #80 
Added pause option when pressing the spacebar and when you again press you can resume the video in `segment.py`.
https://github.com/user-attachments/assets/98e866a5-aa70-4639-9a3f-5a470f782eee
> Add pause functionality to video processing loop

- segmentation_utils.py
> sorted functions

- img_segment.py
- segmentation_utils.py
> color space conversion

- segment.py
> Morphological Operations

- palette.py
Title : DEFAULT FILENAME #95 
Closes #<issue_no:#95>
> adding a default filename

- palette.py
Title : fix Incorrect Color Display and Saving in HSV Palette
Closes #102 
1. **Incorrect Hue Calculation with Wrapping Ranges:**  
- When the lower hue (`LH`) is greater than the upper hue (`UH`), the mid-hue calculation was incorrect.  
- The new implementation correctly handles hue wrap-around by calculating the midpoint accounting for the circular nature of the HSV color space.
2. **Color Display Consistency:**  
- Improved blending of HSV values for more accurate color representation.  
- Midpoint hue, saturation, and value are now properly averaged, preventing incorrect color transitions.
3. **Non-blocking Tkinter Dialogs:**  
- The RGB and HSV input dialogs were blocking the OpenCV event loop, making the app unresponsive until the dialogs were closed.  
- This PR makes the Tkinter …
> Refactor root instance handling and improve non-blocking window behavior

- segment.py
- segmentation_utils.py
Title : fix Incompatible Video Codec and File Extension in segment.py
Closes #96 
This pull request introduces significant improvements to video handling in the `segment.py` and `segmentation_utils.py` files. The changes enhance the flexibility and robustness of video codec selection and loading mechanisms.
Improvements to video codec selection:
* [`segment.py`](diffhunk://#diff-055f4e62558f5326938f7dbe96b8b8ac992924586b895304ef285ab27d2d49d9L76-R98): Added dynamic codec selection with a mapping dictionary to handle various video formats more flexibly. The code now corrects the file extension if necessary and defaults to AVI if the format is unsupported.
Enhancements to video loading:
* [`segmentation_utils.py`](diffhunk://#diff-64e13ceae04b5e0a87b33fd7a6a272ae70184ad0d5f483c0c6fe97f4c2778 …
> fix Incompatible Video Codec and File Extension in segment.py

- app.py
Title : streamlit-UI #114
Closes #<issue_no>
> streamlit-UI #114

- img_segment.py
- palette.py
- segment.py
- segmentation_utils.py
Title : Fix Inefficient Frame Timing Control Leading to High CPU Usage or Lag
Closes #97 
This pull request includes several changes to improve the frame rate control and image loading functionality in the `img_segment.py`, `palette.py`, `segment.py`, and `segmentation_utils.py` files. The most important changes include replacing the use of `time.time()` with `cv2.getTickCount()` for better frame rate control and adding support for loading images from file paths.
Frame rate control improvements:
* [`img_segment.py`](diffhunk://#diff-edb8f3b129c3b13bb610448147a08d7f4a0807c43e57f02e5e75f3c134066eedR108-R112): Replaced `time.time()` with `cv2.getTickCount()` for calculating elapsed time and controlling frame rate in the main loop.
* …
> Fix Inefficient Frame Timing Control Leading to High CPU Usage or Lag

- img_segment.py
- segment.py
- segmentation_utils.py
> morphology redundancy

- img_segment.py
- segment.py
- segmentation_utils.py
> savedimage in bgr

- img_segment.py
- segment.py
- segmentation_utils.py
> Aspect Ratio Distortion in Video Processing

- .gitignore
- app.py
Title : added color palette
Closes #109 
added color palette
https://github.com/user-attachments/assets/5500b366-a68d-4bad-88e4-e3f1edba20ee
> added color palette

- img_segment.py
> save results

- segment.py
> fix: Potential Issues and Enhancements for Video Segmentation Script

- img_segment.py
> fix: z-order issue

- palette.py
> refactor: Palette Tool Fixes and Enhancements

- app.py
> added error handling

- segment.py
> saving issue

- app.py
- img_segment.py
- segment.py
- segmentation_utils.py
> inconsistent color space handling
